
name: LawnShark-App

on:
  push:
    branches: [ "main" ]

jobs:
  LawnShark-App:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: LawnShark-App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWD }}
          port: ${{ secrets.PORT }}
          script: |
            cd Backend_app
            git pull
            
